using UnityEngine;

public class pendulumScript : MonoBehaviour
{
    [SerializeField] float swingForce = 10f; // U‚èq‚É‰Á‚¦‚é—Í‚Ì‘å‚«‚³
    [SerializeField] float maxSwingAngle = 30f; // U‚èq‚ÌÅ‘åU‚è•iŠp“xj

    Rigidbody2D _rb2d;
    Quaternion startRotation;

    void Start()
    {
        _rb2d = GetComponent<Rigidbody2D>();
        startRotation = transform.rotation;
    }

    void FixedUpdate()
    {
        // U‚èq‚ÌŠp“x‚ğŒvZ
        float currentAngle = Quaternion.Angle(startRotation, transform.rotation);

        // Å‘åU‚è•ˆÈã‚É‚È‚Á‚½‚ç—Í‚ğ”½“]‚³‚¹‚é
        if (currentAngle >= maxSwingAngle)
        {
            swingForce = -swingForce;
        }

        // U‚èq‚É—Í‚ğ‰Á‚¦‚é
        _rb2d.AddTorque(swingForce);
    }
}
